### ISSUE TITLE
PSR3 Logger Interface

### ISSUE THREAD

**Issue by bueltge** [bueltge/marksimple#1]
Maybe as alternative for https://github.com/bueltge/marksimple/blob/1.0.0/src/MarkSimple.php#L289
for method `set_error_reporting()` for Active Error Reporting.

```php
setErrorReporting()
```

```php
use Psr\Log\LoggerInterface;
use Psr\Log\NullLogger;

class Marksimple {

    protected $logger;
    
    
    public function __construct(LoggerInterface $logger = null) 
    {
        $this->logger = $logger ?? new NullLogger();
    }

}
```

**Comment by bueltge** [comment]
Leave open, if we need a log function.

**Comment by peter279k** [comment]
How about using the (monolog)[https://github.com/Seldaek/monolog] to complete issue?

The `monolog` package follows the `PSR-3` logger interface.

**Comment by bueltge** [comment]
I would implement a logger for error handling. The current version haven't a error log. So the idea was to implement a logger, like Monolog psr3.

**Comment by peter279k** [comment]
@bueltge, thank you for your reply.

I think we have to implement own `LoggerInterface` with `PSR-3` standard.

I will create the related PR for this.

**Comment by bueltge** [comment]
Wow, that's would be great.

**Comment by peter279k** [comment]
@bueltge, I think we can also add the `Logger usage` section in `README.md`.

Do you have any idea about this?

**Comment by bueltge** [comment]
Yep, that would be fine. Feel free to enhance the readme, there should store this documentation. I need also more solid unit tests for the Logger, currently we check only the class instance, not more.

**Comment by bueltge** [comment]
Hi @peter279k 
I think we should implement a log on `parseFile` so that we log a error if fail is not exists or not readable. This should also use as example for the logger.

**Comment by bueltge** [comment]
I close them, the task is done. Thanks again for your help!
Question, do you use it? In which topic?

**Comment by peter279k** [comment]
Hi @bueltge, thank you for your reply.

I will use this for my personal project for my markdown format strings :).

**Comment by bueltge** [comment]
Thanks, maybe you can link them, so that I see the result, my personal interesting.
